# Site settings
title: ./dotslash
email: ajay.tatachar@gmail.com
description: The blog of a coder.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ajaymt.github.com" # the base hostname & protocol for your site
twitter_username: ajaymadhusudan
github_username:  AjayMT

# Build settings
markdown: kramdown
